name: 'actions-labeler'
description: 'My GitHub Action Labeler'
author: 'Tlaster'
inputs:
  github_token:
    required: true
    description: 'Your github repo token'
  wip_start_with:
    description: 'text to check for start with in title'
    default: '[WIP]'
  wip_label:
    description: 'label to add to PR'
    default: 'WIP'
  ready_label:
    description: 'label to add to PR when ready for review'
    default: 'ready'
  approved_label:
    description: 'label to add to PR when all approved'
    default: 'approved'
runs:
  using: 'node16'
  main: 'dist/index.js'
